[env]
MACOSX_DEPLOYMENT_TARGET = "11.0"
CMAKE_OSX_DEPLOYMENT_TARGET = "11.0"

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-mmacosx-version-min=11.0"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-mmacosx-version-min=11.0"]
